version: '2'
catalog:
  name: "MySQL"
  version: "MySQL_8.0"
  description: "MySQL"
  questions:
  - variable: "mysql_pass"
    description: "Please enter MySQL Root Password"
    label: "Root Password:"
    type: password
  - variable: "project"
    description: "Project Name"
    label: "Project Name:"
    type: string
    default: "Project 1"
services:
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 3306
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  phpMyAdmin:
    scale: 1
    start_on_create: true
networks:
  commonnet:
    external: true